language: bash
dist: bionic
services:
  - docker
script:
  # do not use slow release mode for building
  - sed -i s/--release// solutions/differential/solution.ini
  - ./docker.sh --pull
  - ./docker.sh --build-if-not-fresh
  - ./docker.sh -r
notifications:
  email: false
  on_success: change
  on_failure: always
