language: bash
dist: bionic
services:
  - docker
script:
  - ./docker.sh --pull
  - ./docker.sh --build-if-not-fresh
  - ./docker.sh -r
notifications:
  email: false
  on_success: change
  on_failure: always
