language: bash
dist: bionic
services:
  - docker
install:
  # do not use slow release mode for Rust build
  - sed -i s/--release// solutions/differential*/solution.ini
  - sed -i "s|/release/|/debug/|" solutions/differential*/solution.ini
  - ./docker.sh --pull                  # pull available images
  - ./docker.sh --build-if-not-fresh    # (re)build image if different than current commit
  - docker/set-configs.sh               # copy generic settings from config.json to config-docker-*.json files
script:
  - ./docker.sh -r --java-heap-size 6G  # run measurements
                                        # limit the CPU cores if needed: --cpus 0-7
notifications:
  email: false
  on_success: change
  on_failure: always
