name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Build
        run: |
          # check that all Dockerfiles contain the same run command
          test $(docker/ls-images.sh --runnable | wc -l) -eq $(grep -F "RUN scripts/run.py -b --skip-tests" docker/Dockerfile-* | wc -l)
          # run tests in CI
          sed -i "s|RUN scripts/run.py -b --skip-tests|RUN scripts/run.py -b|" docker/Dockerfile-*
          # do not use slow release mode for Rust build
          sed -i s/--release// solutions/differential*/solution.ini
          sed -i "s|/release/|/debug/|" solutions/differential*/solution.ini
          # TODO: WIP! only build this tool
          ./docker.sh --pull -t common-v2020-11-30
          ./docker.sh --build -t neo4j
          docker/set-configs.sh               # copy generic settings from config.json to config-docker-*.json files
          ./docker.sh -r  -t neo4j  # run measurements
                                              # limit the CPU cores if needed: --cpus 0-7
