name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Build
        run: |
          sed -i s/--release// solutions/differential*/solution.ini
          sed -i "s|/release/|/debug/|" solutions/differential*/solution.ini
          ./docker.sh --pull                  # pull available images
          ./docker.sh --build-if-not-fresh    # (re)build image if different than current commit
          docker/set-configs.sh               # copy generic settings from config.json to config-docker-*.json files
          ./docker.sh -r --java-heap-size 6G  # run measurements
