name: Check image availability
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # monthly trigger
    - cron: "00 11 23 * *"
jobs:
  check_images:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2.3.1
      - name: Check image manifests
        run: |
          DOCKER_REPO=ftsrg/ttc2018
          # evalute brace expansion: https://stackoverflow.com/a/55661486
          TAGS={$(echo -n "$(docker/ls-images.sh --publishable)" | tr '\n' ',')}
          TAG_VERSIONS={,-v2021-05-24}
          eval docker/check-docker-hub-tags.sh $DOCKER_REPO $TAGS$TAG_VERSIONS
